stages:
  - test
  - deploy

jmeter_test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script:
    - echo "Running JMeter Tests for minriftSarath"
    - mvn clean verify
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - results/**/*
      - results/dashboard/**/*
      - target/jmeter/results/**/*
      - target/jmeter/reports/**/*

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r results/dashboard/* .public/
  artifacts:
    paths:
      - .public
  only:
    - main
