<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.minriftSarath</groupId>
    <artifactId>minriftSarath</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>com.lazerycode.jmeter</groupId>
                <artifactId>jmeter-maven-plugin</artifactId>
                <version>3.7.0</version>
                <executions>
                <!-- Configure goal -->
                <execution>
                    <id>configuration</id>
                    <goals>
                        <goal>configure</goal>
                    </goals>
                </execution>
                <!-- Run goal -->
                <execution>
                    <id>jmeter-tests</id>
                    <goals>
                        <goal>jmeter</goal>
                    </goals>
                </execution>
            </executions>
                <configuration>
                    <testFilesIncluded>
                        <jMeterTestFile>TestPlan.jmx</jMeterTestFile>
                    </testFilesIncluded>
                    <resultsDirectory>results</resultsDirectory>
                    <generateReports>true</generateReports>
                    <reportOutputDirectory>results/dashboard</reportOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
